FROM openjdk:8-jdk-alpine

COPY target/naturarv-portal-thorntail.jar /usr/src/myapp/
WORKDIR /usr/src/myapp


ENTRYPOINT [""]
EXPOSE 8080
CMD ["java", "-jar", "naturarv-portal-thorntail.jar", "-Sinitdata"]
